Feature/setup i18n lib
Orange-OpenSource/ods-flutter pull request #115
Opened 2023-04-21 07:20 UTC by Tayebsed93

2023-04-21 07:26 UTC, julien-deramond commented
## Reminder to update the release process of the library

**Development process**

* Developer modify `ods_flutter_en.arb` and/or `ods_flutter_fr.arb`
* In order to have the translations in the app launched locally, `flutter gen-l10n` must be launched in the `lib` directory
  * It will regenerate:
    * `ods_flutter_localizations.dart`
    * `ods_flutter_localizations_en.dart`
    * `ods_flutter_localizations_fr.dart` 
 * The 5 files need to be committed and pushed

**Release the library**
* Pre-step: run `flutter gen-l10n` for security before creating and publishing the package
  * If files are modified, it means that something is wrong (`ods_flutter_localizations*` are maybe not all pushed)

2023-04-21 07:42 UTC, julien-deramond requested changes
Neat!

Only comment on my side: IMO `ods_flutter_localization*` files shouldn't be pushed because generated automatically by `flutter gen-l10n` and added in our `.gitignore`.
It will be clearer that the only files to modify are the `ods_flutter*.arb` and will avoid mistakes in general.

2023-04-21 07:44 UTC, julien-deramond approved these changes

2023-04-21 07:49 UTC, julien-deramond commented
@Tayebsed93 I didn't see it at first but the tests are broken. Might be something to update to make them work again.

2023-04-21 09:25 UTC, julien-deramond requested changes
Based on the internal discussion:

- Lib must contains only wordings used within the lib (we can create a fake one for test purpose, but right now should be rather empty)
- The generation of the files should be done only in the app
- App should have the keys to translate for its own wording
- App should be able to translate the elements in the lib (+ its own) in another language

2023-04-26 08:36 UTC, ludovic35 commented on .github/workflows/demo_app.yml
> +          cd lib
rename lib to library

2023-04-26 08:43 UTC, ludovic35 commented on app/lib/main.dart
> +            OdsLocalizations.delegate,
See if it is mandatory
If yes add a section in ReadMe how to Use

2023-04-26 08:46 UTC, ludovic35 commented on lib/lib/l10n/.gitignore
> +gen/
Remove the gitignore 
and add it at the top level

2023-04-26 13:05 UTC, ludovic35 commented on app/lib/main.dart
> +            OdsLocalizations.delegate,
Done

2023-04-26 13:06 UTC, ludovic35 commented on lib/lib/l10n/.gitignore
> +gen/
Done

2023-04-26 13:16 UTC, merged