124-create component description page structure
Orange-OpenSource/ods-flutter pull request #137
Opened 2023-05-05 14:49 UTC by dolinetouko

2023-05-12 10:32 UTC, Tayebsed93 approved these changes

2023-05-12 13:37 UTC, ludovic35 requested changes

2023-05-22 09:01 UTC, ludovic35 requested changes

2023-05-22 09:52 UTC, paulinea requested changes

2023-05-22 09:52 UTC, paulinea commented on app/assets/il_radiobutton.png
Remove this file cause the equivalent exists in `.svg`

2023-05-22 09:52 UTC, paulinea commented on app/lib/ui/components/component_list.dart
> +            Text("Coming Soon")),
I think we have to remove this variants cause they don't exist for now in the Flutter library and we have dead links.

2023-05-22 09:52 UTC, paulinea commented on app/lib/ui/components/template/component_detail_screen.dart
> +      },
The play icon should be centered vertically in the tile

2023-05-22 09:52 UTC, paulinea commented on app/lib/ui/components/template/component.dart
We discussed about directories with Ludovic and we decided that `component.dart`, `component_detail_screen.dart` and `components_screen.dart` should be moved out of the `template` directory. After that, the `template` directory should be removed.

2023-05-22 09:52 UTC, paulinea commented on app/lib/ui/components/template/component_detail_screen.dart
> +                  bottom: spacingM),
When the padding is the same everywhere, prefer the use of `EdgeInsets.all(spacingM)`

2023-05-22 14:54 UTC, paulinea commented on app/lib/ui/components/component_detail_screen.dart
> +          Icon(Icons.play_circle_outline),
This icon should be the same as in the Android app. Here it is a grey icon, on Android it is black.

2023-05-22 15:30 UTC, paulinea approved these changes

2023-05-22 15:34 UTC, merged