8 - ODS component - cards - image first card
Orange-OpenSource/ods-flutter pull request #156
Opened 2023-05-24 16:17 UTC by paulinea

2023-05-26 10:01 UTC, ludovic35 requested changes

2023-05-30 11:37 UTC, paulinea commented on app/lib/ui/components/cards/card_vertical_image_first.dart
> +import 'package:flutter/material.dart';
Not sure about this one, I think we chose to remove the `component` prefix to have lighter names. But we have to do this progressively.

2023-05-30 11:46 UTC, paulinea commented on library/lib/components/card/ods_vertical_image_first_card.dart
> +  final String? button1Text;
ok, it's a good idea

2023-05-30 13:00 UTC, paulinea commented on app/lib/ui/components/ods_components.dart
> +import 'package:ods_flutter_demo/ui/components/component_entities.dart';
Actually, the list of components could be in `components_screen`. What do you think?

2023-05-30 13:05 UTC, ludovic35 commented on app/lib/ui/components/ods_components.dart
> +import 'package:ods_flutter_demo/ui/components/component_entities.dart';
Good idea

2023-05-30 13:45 UTC, ludovic35 requested changes

2023-05-30 13:56 UTC, paulinea commented on library/lib/components/utilities/ods_button_entity.dart
> +  final VoidCallback? onClick;
a mistake, I fix it

2023-05-30 14:50 UTC, ludovic35 approved these changes

2023-05-30 14:50 UTC, merged