142 update demo app for checkboxes component
Orange-OpenSource/ods-flutter pull request #158
Opened 2023-05-30 10:52 UTC by Tayebsed93

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

### Description

### Motivation & Context

### Types of change

- Bug fix (non-breaking which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)

### Checklist

#### Accessibility

- [X] My change follows accessibility good practices

#### Design

- [X] My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
- [X] My change is compatible with responsive display

#### Documentation

- [X] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [X] Manually test on simulators and on a physical device (Android & iOS, orientation change, dark/light mode)
- [X] Code review
- [X] Design review
- [X] A11y review

2023-06-29 13:30 UTC, ludovic35 requested changes

2023-07-03 12:51 UTC, Tayebsed93 commented on app/lib/ui/components/checkboxes/component_checkboxes.dart
>      return Scaffold(
sorry, can you specify what to do?

2023-07-07 13:09 UTC, ludovic35 commented on app/lib/ui/components/checkboxes/checkboxes.dart
> +                label: 'Butter Checkbox',
Do we need to localize ?

2023-07-07 15:03 UTC, ludovic35 approved these changes

2023-07-07 15:13 UTC, merged