148 - Add bottomsheet to configure components in application
Orange-OpenSource/ods-flutter pull request #163
Opened 2023-06-06 12:51 UTC by paulinea

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

### Description

### Motivation & Context

### Types of change

- Bug fix (non-breaking which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)

### Checklist

#### Accessibility

- [ ] My change follows accessibility good practices

#### Design

- [ ] My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
- [ ] My change is compatible with responsive display

#### Documentation

- [ ] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] Manually test on simulators and on a physical device (Android & iOS, orientation change, dark/light mode)
- [ ] Code review
- [ ] Design review
- [ ] A11y review

2023-06-08 13:34 UTC, ludovic35 requested changes

2023-06-09 08:59 UTC, paulinea commented on library/lib/components/card/ods_small_card.dart
> +class OdsSmallCard extends StatefulWidget {
Otherwise the widget cannot be updated on the flight when you customize it through the customization bottom sheet.

2023-06-09 09:02 UTC, paulinea commented on app/lib/ui/components/cards/card_customization.dart
> +class _CardCustomization extends InheritedWidget {
Not sure about that cause on Android side we use the same customization class for all cards. I think we can try like this and we'll change it if necessary.

2023-06-09 09:10 UTC, paulinea commented on app/lib/ui/components/cards/card_customization.dart
> +import 'package:flutter/material.dart';
Q1: For the moment we don't have specs for bottom sheet so I chose to let it grey
Q2: Fixed

2023-06-09 11:22 UTC, ludovic35 commented on app/lib/ui/components/cards/card_customization.dart
> +class _CardCustomization extends InheritedWidget {
ok

2023-06-09 11:25 UTC, ludovic35 approved these changes

2023-06-09 12:21 UTC, merged